### ISSUE TITLE
Friend list and Stack split

### ISSUE THREAD

**Issue by ghost** [Klixxx/ElvUI_KlixUI-Classic#1]
Message: Interface\AddOns\ElvUI_KlixUI\modules\efl\efl.lua:127: attempt to call field 'GetFriendInfo' (a nil value)
Time: Wed Sep 11 11:13:43 2019
Count: 1
Stack: Interface\AddOns\ElvUI_KlixUI\modules\efl\efl.lua:127: attempt to call field 'GetFriendInfo' (a nil value)
[C]: in function SetAttribute' Interface\FrameXML\UIParent.lua:2526: in function ShowUIPanel'
Interface\FrameXML\FriendsFrame.lua:1113: in function `ToggleFriendsFrame'
[string "TOGGLESOCIAL"]:1: in function <[string "TOGGLESOCIAL"]:1>

Locals: (*temporary) = {
0 =
ShowUIPanel = defined @interface\FrameXML\UIParent.lua:1808
UpdateUIPanelPositions = defined @interface\FrameXML\UIParent.lua:2156
left = FriendsFrame {
}
HideUIPanel = defined @interface\FrameXML\UIParent.lua:2104
ShowUIPanelFailed = defined @interface\FrameXML\UIParent.lua:2014
MoveUIPanel = defined @interface\FrameXML\UIParent.lua:2084
SetUIPanel = defined @interface\FrameXML\UIParent.lua:2020
UIParentManageFramePositions = defined @interface\FrameXML\UIParent.lua:2267
GetUIPanel = defined @interface\FrameXML\UIParent.lua:2148
}
(*temporary) = "panel-show"
(*temporary) = "panel-show"
(*temporary) = true
(*temporary) = defined =[C]:-1
-------------------------------

.s\ElvUI_KlixUI\modules\skins\blizzard\stacksplit.lua:8: attempt to index field 'backdrop' (a nil value)
Count: 1

Call Stack:
(tail call): ?
...s\ElvUI_KlixUI\modules\skins\blizzard\stacksplit.lua:8: in function <...s\ElvUI_KlixUI\modules\skins\blizzard\stacksplit.lua:4>
[C]: ?
ElvUI\Modules\skins\Skins.lua:1312: in function <ElvUI\Modules\skins\Skins.lua:1298>
[C]: ?
ElvUI\Core\Core.lua:1199: in function CallLoadFunc' ElvUI\Core\Core.lua:1214: in function CallLoadedModule'
ElvUI\Core\Core.lua:1240: in function InitializeModules' ElvUI\Core\Core.lua:1450: in function <ElvUI\Core\Core.lua:1429> [C]: in function Initialize'
ElvUI\init.lua:220: in function <ElvUI\init.lua:219>

**Comment by Klixxx** [comment]
That stacksplit error is not there anymore, have you updated KlixUI to latest dev. version?
And how those that efl error happen?

**Comment by ghost** [comment]
Yes, stacksplit error has been fixed.
efl error happens everytime I open the social window

**Comment by ghost** [comment]
Complete error:

Message: Interface\AddOns\ElvUI_KlixUI\modules\efl\efl.lua:127: attempt to call field 'GetFriendInfo' (a nil value)
Time: Wed Sep 11 16:27:51 2019
Count: 1
Stack: Interface\AddOns\ElvUI_KlixUI\modules\efl\efl.lua:127: attempt to call field 'GetFriendInfo' (a nil value)
[C]: in function `FriendsFrame_UpdateFriendButton'
Interface\FrameXML\FriendsFrame.lua:1287: in function `FriendsFrame_UpdateFriends'
Interface\FrameXML\FriendsFrame.lua:604: in function `FriendsList_Update'
Interface\FrameXML\FriendsFrame.lua:325: in function <Interface\FrameXML\FriendsFrame.lua:324>
[C]: ?
[C]: in function `Show'
Interface\FrameXML\UIParent.lua:2078: in function `SetUIPanel'
Interface\FrameXML\UIParent.lua:1923: in function `ShowUIPanel'
Interface\FrameXML\UIParent.lua:1784: in function <Interface\FrameXML\UIParent.lua:1780>
[C]: in function `SetAttribute'
Interface\FrameXML\UIParent.lua:2526: in function `ShowUIPanel'
Interface\FrameXML\FriendsFrame.lua:1113: in function `ToggleFriendsFrame'
[string "TOGGLESOCIAL"]:1: in function <[string "TOGGLESOCIAL"]:1>

Locals: (*temporary) = 34
(*temporary) = <function> defined =[C]:-1
 = <function> defined @Interface\FrameXML\FriendsFrame.lua:1311
 = <function> defined @Interface\AddOns\Decursive\Libs\AceHook-3.0\AceHook-3.0.lua:100

Message: Interface\AddOns\ElvUI_KlixUI\modules\efl\efl.lua:127: attempt to call field 'GetFriendInfo' (a nil value)
Time: Wed Sep 11 16:27:51 2019
Count: 1
Stack: Interface\AddOns\ElvUI_KlixUI\modules\efl\efl.lua:127: attempt to call field 'GetFriendInfo' (a nil value)
[C]: in function `SetAttribute'
Interface\FrameXML\UIParent.lua:2526: in function `ShowUIPanel'
Interface\FrameXML\FriendsFrame.lua:1113: in function `ToggleFriendsFrame'
[string "TOGGLESOCIAL"]:1: in function <[string "TOGGLESOCIAL"]:1>

Locals: (*temporary) = <unnamed> {
 0 = <userdata>
 ShowUIPanel = <function> defined @Interface\FrameXML\UIParent.lua:1808
 UpdateUIPanelPositions = <function> defined @Interface\FrameXML\UIParent.lua:2156
 left = FriendsFrame {
 }
 HideUIPanel = <function> defined @Interface\FrameXML\UIParent.lua:2104
 UIParentManageFramePositions = <function> defined @Interface\FrameXML\UIParent.lua:2267
 MoveUIPanel = <function> defined @Interface\FrameXML\UIParent.lua:2084
 ShowUIPanelFailed = <function> defined @Interface\FrameXML\UIParent.lua:2014
 SetUIPanel = <function> defined @Interface\FrameXML\UIParent.lua:2020
 GetUIPanel = <function> defined @Interface\FrameXML\UIParent.lua:2148
}
(*temporary) = "panel-show"
(*temporary) = "panel-show"
(*temporary) = true
(*temporary) = <function> defined =[C]:-1

Message: Interface\AddOns\ElvUI_KlixUI\modules\efl\efl.lua:127: attempt to call field 'GetFriendInfo' (a nil value)
Time: Wed Sep 11 16:29:46 2019
Count: 6
Stack: Interface\AddOns\ElvUI_KlixUI\modules\efl\efl.lua:127: attempt to call field 'GetFriendInfo' (a nil value)

Locals:
